spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipeApp_pro
    username: bhu_pro
    password: sql@1234
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false